# Generated by Django 2.2.4 on 2022-10-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0019_autor_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre_producto'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['nombre_proveedor'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='apellidos',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='nombre_producto',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nacionalidad',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='titulo',
        ),
        migrations.AddField(
            model_name='autor',
            name='proveedor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='correo_proveedor',
            field=models.EmailField(max_length=255, null=True, verbose_name='Correo proveedor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='nombre_proveedor',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre proveedor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='telefono_proveedor',
            field=models.CharField(max_length=12, null=True, verbose_name='Teléfono proveedor'),
        ),
    ]
