# Generated by Django 2.2.4 on 2022-10-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0020_auto_20221010_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_mesa', models.CharField(max_length=2, null=True, verbose_name='Número de la mesa')),
                ('descripcion_mesa', models.CharField(max_length=255, null=True, verbose_name='Descripción mesa')),
                ('cantidad_personas', models.CharField(max_length=2, null=True, verbose_name='Cantidad de personas')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero_mesa'],
            },
        ),
    ]
