# Generated by Django 2.2.4 on 2022-10-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0022_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=2, null=True, verbose_name='Cantidad')),
                ('productos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libro.Autor')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libro.Libro')),
            ],
            options={
                'verbose_name': 'Bodega',
                'ordering': ['proveedor'],
            },
        ),
    ]
