# Generated by Django 2.2.4 on 2022-10-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0023_bodega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={'ordering': ['proveedor'], 'verbose_name': 'Bodega', 'verbose_name_plural': 'Bodegas'},
        ),
    ]
