# Generated by Django 2.2.4 on 2022-10-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0024_auto_20221018_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('email_cliente', models.EmailField(max_length=255)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('apellido_cliente', models.CharField(max_length=200)),
                ('telefono_cliente', models.CharField(max_length=12)),
                ('fecha_reserva', models.DateField(blank=True, verbose_name='Fecha de la reserva')),
                ('hora_reserva', models.CharField(blank=True, choices=[('15:15', '15:15'), ('16:00', '16:00'), ('13:45', '13:45'), ('14:15', '14:15'), ('14:45', '14:45'), ('15:45', '15:45'), ('15:30', '15:30'), ('16:15', '16:15'), ('16:45', '16:45'), ('13:00', '13:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('16:30', '16:30'), ('13:30', '13:30'), ('13:15', '13:15'), ('14:00', '14:00')], max_length=5, verbose_name='Hora de la reserva')),
                ('numero_mesa', models.ManyToManyField(to='libro.Mesa')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['nombre_cliente'],
            },
        ),
    ]
