# Generated by Django 2.2.4 on 2022-10-22 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0025_auto_20221021_2100'),
        ('cliente', '0008_auto_20221021_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_reserva',
            field=models.CharField(blank=True, choices=[('14:30', '14:30'), ('14:00', '14:00'), ('13:00', '13:00'), ('13:45', '13:45'), ('14:15', '14:15'), ('13:15', '13:15'), ('16:15', '16:15'), ('15:15', '15:15'), ('16:30', '16:30'), ('15:00', '15:00'), ('16:00', '16:00'), ('16:45', '16:45'), ('14:45', '14:45'), ('13:30', '13:30'), ('15:30', '15:30'), ('15:45', '15:45')], max_length=5, null=True, verbose_name='Hora de la reserva'),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='numero_mesa',
        ),
        migrations.AddField(
            model_name='reserva',
            name='numero_mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libro.Mesa'),
        ),
    ]
