# Generated by Django 2.2.4 on 2022-10-24 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_auto_20221021_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_reserva',
            field=models.CharField(blank=True, choices=[('13:15', '13:15'), ('14:15', '14:15'), ('14:45', '14:45'), ('15:45', '15:45'), ('16:00', '16:00'), ('16:45', '16:45'), ('15:30', '15:30'), ('16:15', '16:15'), ('14:00', '14:00'), ('13:00', '13:00'), ('15:00', '15:00'), ('15:15', '15:15'), ('16:30', '16:30'), ('14:30', '14:30'), ('13:30', '13:30'), ('13:45', '13:45')], max_length=5, null=True, verbose_name='Hora de la reserva'),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_a_pagar', models.CharField(max_length=6, verbose_name='Total a pagar')),
                ('fecha_de_pago', models.DateField(verbose_name='Fecha de pago')),
                ('estado_pago', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], max_length=12, null=True, verbose_name='Estado de pago')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email', to='cliente.Reserva')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'ordering': ['total_a_pagar'],
            },
        ),
    ]
