# Generated by Django 2.2.4 on 2022-10-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('rol', models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Garzón', 'Garzón'), ('Bodega', 'Bodega'), ('Finanzas', 'Finanzas'), ('Cocina', 'Cocina')], max_length=14, verbose_name='Rol')),
                ('usuario_activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
