# Generated by Django 2.2.4 on 2022-10-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Finanzas', 'Finanzas'), ('Garzón', 'Garzón'), ('Cocina', 'Cocina'), ('Bodega', 'Bodega')], max_length=14, null=True, verbose_name='Rol'),
        ),
    ]
