# Generated by Django 2.2.4 on 2022-10-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Bodega', 'Bodega'), ('Garzón', 'Garzón'), ('Cocina', 'Cocina'), ('Administrador', 'Administrador'), ('Finanzas', 'Finanzas')], max_length=14, verbose_name='Rol'),
        ),
    ]
