# Generated by Django 2.2.4 on 2022-11-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20221025_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Finanzas', 'Finanzas'), ('Garzón', 'Garzón'), ('Bodega', 'Bodega'), ('Cocina', 'Cocina'), ('Administrador', 'Administrador')], max_length=14, verbose_name='Rol'),
        ),
    ]
