# Generated by Django 2.2.4 on 2022-11-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20221114_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Garzón', 'Garzón'), ('Bodega', 'Bodega'), ('Cocina', 'Cocina'), ('Finanzas', 'Finanzas')], max_length=14, verbose_name='Rol'),
        ),
    ]
