# Generated by Django 2.2.4 on 2022-11-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20221114_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Finanzas', 'Finanzas'), ('Bodega', 'Bodega'), ('Garzón', 'Garzón'), ('Administrador', 'Administrador'), ('Cocina', 'Cocina')], max_length=14, verbose_name='Rol'),
        ),
    ]
