# Generated by Django 2.2.4 on 2022-11-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20221115_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Bodega', 'Bodega'), ('Cocina', 'Cocina'), ('Finanzas', 'Finanzas'), ('Garzón', 'Garzón')], max_length=14, verbose_name='Rol'),
        ),
    ]
