# Generated by Django 2.2.4 on 2022-10-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20221018_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Finanzas', 'Finanzas'), ('Bodega', 'Bodega'), ('Cocina', 'Cocina'), ('Administrador', 'Administrador'), ('Garzón', 'Garzón')], max_length=14, null=True, verbose_name='Rol'),
        ),
    ]
