# Generated by Django 2.2.4 on 2022-10-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20221018_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Cocina', 'Cocina'), ('Finanzas', 'Finanzas'), ('Garzón', 'Garzón'), ('Bodega', 'Bodega')], max_length=14, null=True, verbose_name='Rol'),
        ),
    ]
