# Generated by Django 2.2.4 on 2022-11-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_auto_20221115_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Cocina', 'Cocina'), ('Bodega', 'Bodega'), ('Garzón', 'Garzón'), ('Finanzas', 'Finanzas'), ('Administrador', 'Administrador')], max_length=14, verbose_name='Rol'),
        ),
    ]
