# Generated by Django 2.2.4 on 2022-10-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_auto_20221019_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Garzón', 'Garzón'), ('Bodega', 'Bodega'), ('Cocina', 'Cocina'), ('Administrador', 'Administrador'), ('Finanzas', 'Finanzas')], max_length=14, null=True, verbose_name='Rol'),
        ),
    ]
