# Generated by Django 2.2.4 on 2022-10-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_auto_20221021_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Cocina', 'Cocina'), ('Garzón', 'Garzón'), ('Finanzas', 'Finanzas'), ('Administrador', 'Administrador'), ('Bodega', 'Bodega')], max_length=14, null=True, verbose_name='Rol'),
        ),
    ]
