# Generated by Django 2.2.4 on 2022-10-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_auto_20221021_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Finanzas', 'Finanzas'), ('Cocina', 'Cocina'), ('Garzón', 'Garzón'), ('Bodega', 'Bodega'), ('Administrador', 'Administrador')], max_length=14, verbose_name='Rol'),
        ),
    ]
