# Generated by Django 2.2.4 on 2022-10-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0027_auto_20221021_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Garzón', 'Garzón'), ('Administrador', 'Administrador'), ('Cocina', 'Cocina'), ('Bodega', 'Bodega'), ('Finanzas', 'Finanzas')], max_length=14, verbose_name='Rol'),
        ),
    ]
