# Generated by Django 2.2.4 on 2022-10-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0028_auto_20221021_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Garzón', 'Garzón'), ('Finanzas', 'Finanzas'), ('Cocina', 'Cocina'), ('Bodega', 'Bodega'), ('Administrador', 'Administrador')], max_length=14, verbose_name='Rol'),
        ),
    ]
