# Generated by Django 2.2.4 on 2022-11-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0002_auto_20221025_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen_receta',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='receta',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='stock',
            field=models.PositiveIntegerField(null=True, verbose_name='Stock de la receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='precio_receta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de la receta'),
        ),
        migrations.AlterIndexTogether(
            name='receta',
            index_together={('id', 'slug')},
        ),
    ]
