# Generated by Django 2.2.4 on 2022-11-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0003_auto_20221114_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nombre_receta',
            field=models.CharField(max_length=255, verbose_name='Nombre de la receta'),
        ),
    ]
