# Generated by Django 2.2.4 on 2022-11-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0004_auto_20221114_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='imagen_receta',
        ),
        migrations.AddField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/imagenes_receta'),
        ),
    ]
