# Generated by Django 2.2.4 on 2022-11-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0005_auto_20221115_0039'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='receta',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='receta',
            name='slug',
        ),
    ]
