# Generated by Django 2.2.4 on 2022-11-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0007_auto_20221115_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, upload_to='mantenedor/listar_recetas/recetas'),
        ),
    ]
