# Generated by Django 2.2.4 on 2022-11-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0010_auto_20221115_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='stock',
        ),
    ]
