# Generated by Django 2.2.4 on 2022-11-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0011_remove_receta_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, upload_to='recetas'),
        ),
    ]
