# Generated by Django 2.2.4 on 2022-11-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0012_auto_20221115_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='precio_receta',
            field=models.FloatField(max_length=10, verbose_name='Precio de la receta'),
        ),
    ]
