# Generated by Django 2.2.4 on 2022-11-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0013_auto_20221122_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nombre_receta',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre de la receta'),
        ),
    ]
