# Generated by Django 2.2.4 on 2022-11-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0014_auto_20221127_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, upload_to='recetas y bebestibles'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre_receta',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre de la receta o bebestible'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='precio_receta',
            field=models.FloatField(max_length=10, verbose_name='Precio de la receta o bebestible'),
        ),
    ]
