# Generated by Django 2.0.6 on 2022-08-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0009_auto_20220828_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
