# Generated by Django 2.0.6 on 2022-08-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0016_auto_20220828_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='libro.Autor'),
        ),
    ]
