# Generated by Django 2.2.4 on 2022-10-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0021_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_receta', models.CharField(max_length=255, null=True, verbose_name='Nombre de la receta')),
                ('precio_receta', models.CharField(max_length=7, null=True, verbose_name='Precio de la receta')),
                ('tiempo_preparacion', models.CharField(max_length=200, null=True, verbose_name='Tiempo de preparación')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['nombre_receta'],
            },
        ),
    ]
