# Generated by Django 2.2.4 on 2022-10-22 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0024_auto_20221018_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libro.Libro'),
        ),
    ]
