# Generated by Django 2.2.4 on 2022-11-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0013_auto_20221122_0411'),
        ('cliente', '0023_auto_20221122_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('apellido_cliente', models.CharField(max_length=50, null=True, verbose_name='Apellido')),
                ('email_cliente', models.EmailField(max_length=255, null=True)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('ha_pagado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'OrdenCompra',
                'verbose_name_plural': 'OrdenCompras',
                'ordering': ('-fecha_orden',),
            },
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_reserva',
            field=models.CharField(blank=True, choices=[('15:45', '15:45'), ('13:30', '13:30'), ('13:45', '13:45'), ('14:00', '14:00'), ('14:15', '14:15'), ('15:00', '15:00'), ('15:15', '15:15'), ('13:15', '13:15'), ('16:00', '16:00'), ('14:45', '14:45'), ('16:30', '16:30'), ('16:45', '16:45'), ('15:30', '15:30'), ('16:15', '16:15'), ('13:00', '13:00'), ('14:30', '14:30')], max_length=5, null=True, verbose_name='Hora de la reserva'),
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_receta', models.FloatField(max_length=10, verbose_name='Precio de la receta')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='cliente.OrdenCompra')),
                ('receta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_items', to='mantenedor.Receta')),
            ],
        ),
    ]
