# Generated by Django 2.2.4 on 2022-11-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0026_auto_20221127_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], max_length=12, null=True, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_reserva',
            field=models.CharField(blank=True, choices=[('15:00', '15:00'), ('13:30', '13:30'), ('13:45', '13:45'), ('13:15', '13:15'), ('13:00', '13:00'), ('15:15', '15:15'), ('15:45', '15:45'), ('14:45', '14:45'), ('16:15', '16:15'), ('14:15', '14:15'), ('14:30', '14:30'), ('16:00', '16:00'), ('16:45', '16:45'), ('14:00', '14:00'), ('15:30', '15:30'), ('16:30', '16:30')], max_length=5, null=True, verbose_name='Hora de la reserva'),
        ),
    ]
