# Generated by Django 2.2.4 on 2022-11-29 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0014_auto_20221127_0941'),
        ('cliente', '0041_auto_20221128_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedor.Mesa'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_reserva',
            field=models.CharField(blank=True, choices=[('14:15', '14:15'), ('13:00', '13:00'), ('16:00', '16:00'), ('13:30', '13:30'), ('14:45', '14:45'), ('15:15', '15:15'), ('16:15', '16:15'), ('15:30', '15:30'), ('15:45', '15:45'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:30', '16:30'), ('16:45', '16:45'), ('13:45', '13:45'), ('14:30', '14:30'), ('13:15', '13:15')], max_length=5, null=True, verbose_name='Hora de la reserva'),
        ),
    ]
