# Generated by Django 2.2.4 on 2022-11-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0043_auto_20221130_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenitem',
            name='pedido',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_reserva',
            field=models.CharField(blank=True, choices=[('13:30', '13:30'), ('16:30', '16:30'), ('14:00', '14:00'), ('13:15', '13:15'), ('13:45', '13:45'), ('14:30', '14:30'), ('15:00', '15:00'), ('13:00', '13:00'), ('14:15', '14:15'), ('15:15', '15:15'), ('15:30', '15:30'), ('15:45', '15:45'), ('16:00', '16:00'), ('16:15', '16:15'), ('14:45', '14:45'), ('16:45', '16:45')], max_length=5, null=True, verbose_name='Hora de la reserva'),
        ),
    ]
