# Generated by Django 2.2.4 on 2022-10-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20221010_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Bodega', 'Bodega'), ('Garzón', 'Garzón'), ('Administrador', 'Administrador'), ('Cocina', 'Cocina'), ('Finanzas', 'Finanzas')], max_length=14, null=True, verbose_name='Rol'),
        ),
    ]
