# Generated by Django 2.2.4 on 2022-10-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_auto_20221019_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Garzón', 'Garzón'), ('Finanzas', 'Finanzas'), ('Administrador', 'Administrador'), ('Cocina', 'Cocina'), ('Bodega', 'Bodega')], max_length=14, null=True, verbose_name='Rol'),
        ),
    ]
