# Generated by Django 2.2.4 on 2022-10-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0019_auto_20221021_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Finanzas', 'Finanzas'), ('Administrador', 'Administrador'), ('Cocina', 'Cocina'), ('Bodega', 'Bodega'), ('Garzón', 'Garzón')], max_length=14, null=True, verbose_name='Rol'),
        ),
    ]
