# Generated by Django 2.2.4 on 2022-10-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0025_auto_20221021_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_administrador',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Bodega', 'Bodega'), ('Finanzas', 'Finanzas'), ('Cocina', 'Cocina'), ('Garzón', 'Garzón')], max_length=14, null=True, verbose_name='Rol'),
        ),
    ]
