# Generated by Django 2.2.4 on 2022-10-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0029_auto_20221024_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Garzón', 'Garzón'), ('Administrador', 'Administrador'), ('Bodega', 'Bodega'), ('Finanzas', 'Finanzas'), ('Cocina', 'Cocina')], max_length=14, verbose_name='Rol'),
        ),
    ]
